Repository ConvergenceSwAce/22-F-SchoolMeal, pull requests merged in 2022-10, with the labels that each got.

#14 Feat : 데이터 크롤러 완성
  crawling.py
Labels: ✅완료, 👀리뷰, 성중

#19 Feat : Header, WeekCarousel 추가, svg 패키지 추가(삭제 예정)
  MyongJunSickFE/.svgrrc
  MyongJunSickFE/App.js
  MyongJunSickFE/assets/CalendarIcon.png
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/metro.config.js
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: 👨🏻‍💻작업중, 태강

#20 Design : 컴포넌트 디자인 추가
  MyongJunSickFE/App.js
Labels: 👨🏻‍💻작업중, 민수, 태강

#21 Feat : WeekCarousel Button Event 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 태강

#22 Feat : 디자인 1차 완성
  MyongJunSickFE/.env
  MyongJunSickFE/App.js
  MyongJunSickFE/android/app/build.gradle
  MyongJunSickFE/android/app/src/main/java/com/myongjunsickfe/MainApplication.java
  MyongJunSickFE/android/settings.gradle
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/metro.config.js
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 👥논의필요, 태강

#27 Feat : 버튼 클릭시 모달창 및 버튼 기능구현
  MyongJunSickFE/.prettierrc.js
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Btn.jsx
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: 👨🏻‍💻작업중, 민수

#30 Feat : 만족도 설문 Modal Design 추가, 헤더 식당 정보 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Btn.jsx
  MyongJunSickFE/components/Footer.jsx
  MyongJunSickFE/components/Header.jsx
  MyongJunSickFE/components/ListItems.jsx
  MyongJunSickFE/components/MealTiltle.jsx
  MyongJunSickFE/components/WeekCarousel.jsx
Labels: ✅완료, 태강

#34 Feat : 데이터 비동기 처리 및 week Carousel 디자인 변경
  MyongJunSickFE/App.js
  MyongJunSickFE/components/WeekCarousel.jsx
Labels: 👨🏻‍💻작업중, 태강

#35 Feat : Footer 디자인 수정, 실제 날짜 동기화 오류 수정
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Footer.jsx
Labels: ✅완료, 태강

#36 Chore : 로딩 컴포넌트 삭제, 컴포넌트 정리
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Header.jsx
  MyongJunSickFE/components/Loading.jsx
Labels: 👀리뷰, 태강

#37 Chore : dependency 업데이트
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: 👀리뷰, 민수

#38 Fix : eslint 수정
  MyongJunSickFE/.eslintrc.js
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 태강

#40 Feat : Recoil State 관리 추가, 현재 시간 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/ListItems.js
  MyongJunSickFE/components/MealSatisfaction.js
  MyongJunSickFE/components/MealTiltle.js
  MyongJunSickFE/components/MenuList.js
  MyongJunSickFE/components/RecoilApp.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/pages/main.jsx
  MyongJunSickFE/states/index.js
  MyongJunSickFE/yarn.lock
Labels: 👨🏻‍💻작업중, 👀리뷰, 태강

#41 Feat : 요일 터지시 메뉴 불러오기 #28
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/ListItems.js
  MyongJunSickFE/components/MenuList.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/states/index.js
Labels: ✅완료, 민수, 태강

#42 Build : 빌드관련 커밋
  MyongJunSickFE/App.js
  MyongJunSickFE/android/app/src/main/AndroidManifest.xml
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
  MyongJunSickFE/states/index.js
Labels: ✅완료, 민수, 태강

#43 Feat : Splash 화면 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/assets/images/CalendarIcon.png
  MyongJunSickFE/assets/images/Logo.png
  MyongJunSickFE/assets/images/landing_background.jpg
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/Splash.js
Labels: ✅완료, 태강

#44 Feat : 오늘 날짜만 설문 띄우기, 설문 참여 후 컴포넌트 삭제
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/components/DinnerForm.js
  MyongJunSickFE/components/LunchForm.js
  MyongJunSickFE/states/index.js
Labels: ✅완료, 태강

#45 HotFix : 따옴표 변경
  MyongJunSickFE/android/app/src/main/AndroidManifest.xml
Labels: 🐞버그, ✅완료, 태강

#46 Style : 플랫폼 별 StatusBar 높이에 따른 margin 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 태강

#47 HotFix : StatusBar 수정
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Header.js
Labels: 🐞버그, ✅완료, 태강

#48 Design : 상태바 높이 조정
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Header.js
Labels: ✅완료, 민수, 태강

#54 HotFix : 학식 중식메뉴에 따른 컴포넌트 변경
  MyongJunSickFE/App.js
  MyongJunSickFE/assets/images/Logo.png
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/LunchForm.js
  MyongJunSickFE/components/Splash.js
Labels: ✅완료, 태강

#55 Design : 캘린더 짤림 수정
  MyongJunSickFE/components/Header.js
Labels: ✅완료, 태강

#56 Fix : 버튼 클릭시 빈리스트인데도 컴포넌트 삭제됨
  MyongJunSickFE/android/app/src/main/res/values/strings.xml
  MyongJunSickFE/components/Btn.js
Labels: ✅완료, 👀리뷰, 민수

#57 Feat : 사용자 디바이스 uuid 가져오기 #52
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 민수

#63 Build : 아이콘 추가 #62
  MyongJunSickFE/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_back.png
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_back.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_back.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_back.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_back.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  MyongJunSickFE/ios/MyongJunSickFE.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/1024.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/120 1.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/120.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/180.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/40.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/58.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/60.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/80.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/87.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: ✅완료, 민수

#64 Master merge
  MyongJunSickFE/android/app/src/main/AndroidManifest.xml
  MyongJunSickFE/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_adaptive_fore.png
  MyongJunSickFE/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: ✅완료, 민수

#65 Style : 스플래시 스크린 백그라운드 변경
  MyongJunSickFE/components/Splash.js
Labels: ✅완료, 태강

#66 Build : ios로고 이미지 변경
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/1024.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/120 1.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/120.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/180.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/40.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/58.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/60.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/80.png
  MyongJunSickFE/ios/MyongJunSickFE/Images.xcassets/AppIcon.appiconset/87.png
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 민수

#67 Refactor : 주석 처리
  MyongJunSickFE/components/Btn.js
Labels: 👀리뷰, 민수

#68 HotFix : 다크모드 상태 상태바 수정, 개발 ID 부여, 코드 최적화, 스크롤바 숨기기 등
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/ios/Launch Screen.storyboard
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/xcshareddata/xcschemes/MyongJunSickFE.xcscheme
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
Labels: ✅완료, 👀리뷰, 태강

#69 Chore : API 문제 해결
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
Labels: ✅완료, 👀리뷰, 태강

#70 HotFix : PostData 수정
  MyongJunSickFE/components/Btn.js
Labels: ✅완료, 👀리뷰, 태강

#71 Build : gradle 변경
  MyongJunSickFE/android/app/build.gradle
  MyongJunSickFE/android/gradle.properties
  MyongJunSickFE/package.json
Labels: ✅완료, 👀리뷰, 민수

#72 Build : 비공개 테스트 번들 빌드를 위해 버전명 변경
  MyongJunSickFE/android/app/build.gradle
Labels: 민수

#73 Fix : 앱 번들 표시 이름 변경, 런처 스크린 색상 변경
  MyongJunSickFE/ios/Launch Screen.storyboard
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
Labels: ✅완료, 👀리뷰, 태강

#77 Build : 1.1 버전 테스트 및 에러 처리, Chore : 날짜 정보 없을 때 월요일로 고정
  MyongJunSickFE/App.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/ios/Launch Screen.storyboard
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
Labels: ✅완료, 👀리뷰, 태강

#78 Chore : monday Press 추가 수정
  MyongJunSickFE/components/WeekCarousel.js
Labels: ✅완료, 👀리뷰, 태강

#81 HotFix : 자연캠 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/states/index.js
Labels: ✅완료, 👀리뷰, 태강

#82 Fix : PostData 캠퍼스 추가, 수정
  MyongJunSickFE/components/Btn.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/xcshareddata/xcschemes/MyongJunSickFE.xcscheme
Labels: ✅완료, 태강

#83 Build : 빌드버전 변경 (자캠 추가)
  MyongJunSickFE/App.js
  MyongJunSickFE/android/app/build.gradle
Labels: 민수

#85 HotFix : Fir -> Fri 수정
  MyongJunSickFE/components/WeekCarousel.js
Labels: ✅완료, 👀리뷰, 태강

#86 HotFix : 금요일 버튼 수정
  MyongJunSickFE/components/WeekCarousel.js
Labels: ✅완료, 👀리뷰, 태강

#87 Feat : Code-push ios 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE/AppDelegate.mm
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/package.json
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 태강

#90 Fix : 글꼴 고정 오류 제거
  MyongJunSickFE/App.js
Labels: 🐞버그, 민수

#91 Refactor : 서울 캠 컴포넌트 구조 다시짬
  MyongJunSickFE/App.js
  MyongJunSickFE/components/LunchForm.js
  MyongJunSickFE/components/MealCarousel.js
  MyongJunSickFE/components/MenuList.js
  MyongJunSickFE/pages/SeoulCamView.js
Labels: ✅완료, 민수

#93 Design : 인문캠 Carousel 디자인 수정 및 WeekCarousel 수정
  MyongJunSickFE/components/LunchForm.js
  MyongJunSickFE/components/MealCarousel.js
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/pages/SeoulCamView.js
Labels: ✅완료, 👀리뷰, 태강

#94 Feat : 자연캠퍼스 모든 기능구현 #88
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Cafeteria.js
  MyongJunSickFE/components/CafeteriaCarousel.js
  MyongJunSickFE/pages/YonginCamView.js
Labels: ✅완료, 민수

#95 Fix : 진짜끝...
  MyongJunSickFE/components/CafeteriaCarousel.js
Labels: ✅완료, 민수

#96 Fix : 버튼 클릭시 사라지게함 + 맨아래 margin추가
  MyongJunSickFE/assets/images/CalendarIcon.png
  MyongJunSickFE/components/Cafeteria.js
  MyongJunSickFE/components/MealCarousel.js
  MyongJunSickFE/pages/SeoulCamView.js
  MyongJunSickFE/pages/YonginCamView.js
  MyongJunSickFE/states/index.js
Labels: ✅완료, 민수, 태강

#97 Chore : WeekCarousel Flex 수정, ios 버전 수정
  MyongJunSickFE/components/WeekCarousel.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
Labels: ✅완료, 태강

#104 Design: 폰트 크기 전면 수정
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/MealTiltle.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/MyongJunSickFE/Info.plist
Labels: ✅완료, 👀리뷰, 태강

#105 Feat : Footer, 환경설정 모달 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/CafeteriaCarousel.js
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/SettingModal.js
  MyongJunSickFE/pages/SeoulCamView.js
  MyongJunSickFE/pages/YonginCamView.js
Labels: ✅완료, 👀리뷰, 태강

#106 Feat : 첫화면 캠퍼스 지정 캐시 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Cafeteria.js
  MyongJunSickFE/components/CafeteriaCarousel.js
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/Header.js
  MyongJunSickFE/components/SettingModal.js
  MyongJunSickFE/ios/MyongJunSickFE.xcodeproj/project.pbxproj
  MyongJunSickFE/ios/Podfile.lock
  MyongJunSickFE/package-lock.json
  MyongJunSickFE/package.json
  MyongJunSickFE/pages/SeoulCamView.js
  MyongJunSickFE/pages/YonginCamView.js
  MyongJunSickFE/yarn.lock
Labels: ✅완료, 👀리뷰, 태강

#107 Feat : 캠퍼스 환경설정 Recoil 추가
  MyongJunSickFE/App.js
  MyongJunSickFE/components/Cafeteria.js
  MyongJunSickFE/components/CafeteriaCarousel.js
  MyongJunSickFE/components/Footer.js
  MyongJunSickFE/components/SettingModal.js
  MyongJunSickFE/pages/SeoulCamView.js
  MyongJunSickFE/pages/YonginCamView.js
  MyongJunSickFE/states/index.js
Labels: ✅완료, 👀리뷰, 태강

#108 Design : Footer Padding 수정
  MyongJunSickFE/components/Footer.js
Labels: ✅완료, 👀리뷰, 태강

#111 Design : 폰트 수정
  MyongJunSickFE/components/SettingModal.js
  MyongJunSickFE/ios/Podfile.lock
Labels: ✅완료, 👀리뷰, 태강
